apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ibmjj
  name: ibmjj
  namespace: demolab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ibmjj
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ibmjj
    spec:
      containers:
      - image: docker.io/someara/ibmjj:1.0.0
        imagePullPolicy: Always
        name: ibmjj
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 80
      - image: someara/zerotier:latest
        args: [ "12ac4a1e71a909e8" ]
        imagePullPolicy: IfNotPresent
        name: kube-zt
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/net
          name: dev-net
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/net
          type: ""
        name: dev-net
status:
